package com.kasigrill.ordering_system.customer;

public enum BotState {
    GREETING,AWAITING_MAIN_MENU_INPUT,ON_ORDERS_REQUESTED,ON_HELPLINE_REQUESTED,AWAITING_CUSTOMER_NAME,AWAITING_CUSTOMER_NUMBER,AWAITING_CUSTOMER_LOCATION,AWAITING_TERMINATION_INPUT,DONE
}
